name: base

on:
  push:
    branches: 
      - devel
  pull_request:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    name: build

    runs-on: ubuntu-20.04

    container:
      image: centos:7.9.2009
      options: --user root

    env:
      R_VERSION: "4.2.0"
      UNIXODBC_VERSION: "2.3.9"
      DEVTOOLSET_VERSION: "10"
      REPOSITORY: "the-tobias-project/odbc-module"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare general environment
        run: |
          yum update -y && yum makecache && yum clean all
          yum install -y gcc gcc-c++ kernel-devel dnf make cmake 
          yum install -y epel-release 
          yum install -y Lmod git curl wget
          useradd -m sherlock
      - name: Prepare specific R environment
        run: |
          yum install -y libgfortran5 readline readline-devel libicu libicu-devel gcc-gfortran zlib-devel bzip2-devel \
                         libcurl-devel xz-devel pcre2-devel ncurses-devel texinfo gtk+-devel gtk2-devel qt-devel tcl-devel tk-devel \
                         kernel-headers kernel-devel readline-devel unixODBC-devel
      - name: Update devtoolset
        run: | 
          yum -y install centos-release-scl
          yum -y install devtoolset-${{ env.DEVTOOLSET_VERSION }}
          scl enable devtoolset-${{ env.DEVTOOLSET_VERSION }} bash
          echo "source /opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/enable" >> /home/sherlock/.bashrc
      - name: Download and install unixODBC
        run: |
          curl -O ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-${{ env.UNIXODBC_VERSION }}.tar.gz
          tar xf unixODBC-${{ env.UNIXODBC_VERSION }}.tar.gz
          cd unixODBC-${{ env.UNIXODBC_VERSION }}
          ./configure --prefix=/usr --sysconfdir=/etc/unixODBC
          make
          make install
          odbcinst --version
      - name: Install R 
        run: | 
          export R_VERSION=${{ env.R_VERSION }}
          wget https://cran.r-project.org/src/base/R-4/R-${{ env.R_VERSION }}.tar.gz
          tar xvf R-${{ env.R_VERSION }}.tar.gz
          cd R-${{ env.R_VERSION }}
          ./configure --prefix=/share/apps/R-${{ env.R_VERSION }} --with-recommended-packages=no --without-x --with-cairo --with-libpng --with-libtiff --with-jpeglib --enable-R-shlib
          make && make install
      - name: Create unixODBC module
        run: |
          mkdir -p /home/sherlock/.local/share/modulefiles/unixodbc
          echo "setenv('ODBC_HOME', '/usr')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "prepend_path('PATH', '/usr/bin')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "prepend_path('LD_LIBRARY_PATH', '/usr/lib64')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "prepend_path('PKG_CONFIG_PATH', '/usr/lib64/pkgconfig')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "setenv('ODBCSYSINI', '/etc/unixODBC')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
      - name: Create Lua module for R version
        run: |
          mkdir -p /home/sherlock/.local/share/modulefiles/R 
          echo "setenv('R_HOME', '/share/apps/R-${{ env.R_VERSION }}')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "prepend_path('PATH', '/share/apps/R-${{ env.R_VERSION }}/bin')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "prepend_path('LD_LIBRARY_PATH', '/share/apps/R-${{ env.R_VERSION }}/lib64')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "setenv('R', '/usr/local/bin/R')"  >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
        shell: bash
      - name: Prepare the environment
        run: |
          su - sherlock 
          echo "export MODULEPATH=/home/sherlock/.local/share/modulefiles:\$MODULEPATH" >> /home/sherlock/.bashrc
          echo "module use --append /home/sherlock/.local/share/modulefiles/"  >> /home/sherlock/.bashrc
          echo "source /etc/profile.d/z00_lmod.sh" >> /home/sherlock/.bashrc
      - name: Test R module
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          echo $MODULEPATH
          module spider
          module load R/${{ env.R_VERSION }}
          R -e "print('hello')"   
        if: always()
      - name: testing odbc
        run: | 
          su - sherlock 
          source /home/sherlock/.bashrc
          mkdir /home/sherlock/test
          export R_LIBS_USER=/home/sherlock/test
          module load R/4.2.0
          module load unixodbc/2.3.9
          mkdir -p ~/.R/
          echo "CC=/opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/root/bin/gcc" > ~/.R/Makevars
          echo "CXX=/opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/root/bin/g++" >> ~/.R/Makevars
          R --vanilla <<EOF
          install.packages(c('odbc'), repos='http://cran.us.r-project.org', lib=Sys.getenv("R_LIBS_USER"), type="source")
          EOF
        if: always()
      - name: Download repository
        run: | 
          su - sherlock 
          git clone https://github.com/the-tobias-project/odbc-module
          cd odbc-module 
          git checkout $(echo $GITHUB_REF | sed 's/refs\/heads\///')
      - name: Install R modules
        run: |
          su - sherlock    
          source /home/sherlock/.bashrc
          cd /home/sherlock
          mkdir -p ~/.R/
          echo "CC=/opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/root/bin/gcc" > ~/.R/Makevars
          echo "CXX=/opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/root/bin/g++" >> ~/.R/Makevars
          export HOME=/home/sherlock
          bash $PWD/scripts/install_R_modules.sh
      - name: Install drivers
        run: |
          su - sherlock 
          bash $PWD/scripts/install_packages.sh check=false
      - name: Configure
        run: |
          su - sherlock 
          cd /home/sherlock/odbc-module
          make configure group=false
        if: always()
      - name: Setenv
        run: |
          su - sherlock
          cd /home/sherlock/odbc-module
          make setenv group=false
          module spider databricks | grep R/${{ inputs.R_VERSION }}
        if: always()
      - name: Create tarball of artifacts
        run: tar -czvf base.tar.gz /home/sherlock/odbc-module
        working-directory: /home/sherlock
        if: ${{ github.event_name == 'pull_request' }}
      - name: Publish artifact to release page
        uses: actions/upload-release-asset@v1
        with:
          asset_path: base.tar.gz 
          asset_name: odbc-centos7-R_${{ env.R_VERSION }}-devtoolset_${{ env.DEVTOOLSET_VERSION }}-unixodbc_${{ env.UNIXODBC_VERSION }}.tar.gz 
          asset_content_type: application/gzip 
          tag_name: ${{ github.ref }} 
          repository: ${{ env.REPOSITORY }}
        if: ${{ github.event_name == 'pull_request' }}
