name: base

on:
  push:
    branches: 
      - devel
  pull_request:
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    environment: odbc

    container:
      image: centos:7.9.2009
      options: --user root

    env:
      R_VERSION: "4.2.0"
      UNIXODBC_VERSION: "2.3.9"
      DEVTOOLSET_VERSION: "10"
      REPOSITORY: "the-tobias-project/odbc-module"
      HOME: /home/sherlock
    

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare general environment
        run: |
          yum update -y && yum makecache && yum clean all
          yum install -y gcc gcc-c++ kernel-devel dnf make cmake 
          yum install -y epel-release 
          yum install -y Lmod git curl wget
          useradd -m sherlock
      - name: Prepare specific R environment
        run: |
          yum install -y libgfortran5 readline readline-devel libicu libicu-devel gcc-gfortran zlib-devel bzip2-devel \
                         libcurl-devel xz-devel pcre2-devel ncurses-devel texinfo gtk+-devel gtk2-devel qt-devel tcl-devel tk-devel \
                         kernel-headers kernel-devel readline-devel unixODBC-devel 
      - name: Update devtoolset
        run: | 
          yum -y install centos-release-scl
          yum -y install devtoolset-${{ env.DEVTOOLSET_VERSION }}
          yum install -y devtoolset-${{ env.DEVTOOLSET_VERSION }}-gcc-c++
          source /opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/enable
          echo "source /opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/enable" >> /home/sherlock/.bashrc
      - name: Download and install unixODBC
        run: |
          curl -O ftp://ftp.unixodbc.org/pub/unixODBC/unixODBC-${{ env.UNIXODBC_VERSION }}.tar.gz
          tar xf unixODBC-${{ env.UNIXODBC_VERSION }}.tar.gz
          cd unixODBC-${{ env.UNIXODBC_VERSION }}
          ./configure --prefix=/usr --sysconfdir=/etc/unixODBC
          make
          make install
          odbcinst --version
      - name: Install R 
        run: | 
          export R_VERSION=${{ env.R_VERSION }}
          wget https://cran.r-project.org/src/base/R-4/R-${{ env.R_VERSION }}.tar.gz
          tar xvf R-${{ env.R_VERSION }}.tar.gz
          cd R-${{ env.R_VERSION }}
          ./configure --prefix=/share/apps/R-${{ env.R_VERSION }} --with-recommended-packages=no --without-x --with-cairo --with-libpng --with-libtiff --with-jpeglib --enable-R-shlib
          make && make install
      - name: Create unixODBC module
        run: |
          mkdir -p /home/sherlock/.local/share/modulefiles/unixodbc
          echo "setenv('ODBC_HOME', '/usr')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "prepend_path('PATH', '/usr/bin')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "prepend_path('LD_LIBRARY_PATH', '/usr/lib64')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "prepend_path('PKG_CONFIG_PATH', '/usr/lib64/pkgconfig')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
          echo "setenv('ODBCSYSINI', '/etc/unixODBC')" >> /home/sherlock/.local/share/modulefiles/unixodbc/${{ env.UNIXODBC_VERSION }}.lua
      - name: Create Lua module for R version
        run: |
          mkdir -p /home/sherlock/.local/share/modulefiles/R 
          echo "setenv('R_HOME', '/share/apps/R-${{ env.R_VERSION }}')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "prepend_path('PATH', '/share/apps/R-${{ env.R_VERSION }}/bin')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "prepend_path('LD_LIBRARY_PATH', '/share/apps/R-${{ env.R_VERSION }}/lib64')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "setenv('R', '/share/apps/R-${{ env.R_VERSION }}/bin/R')"  >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
        shell: bash
      - name: Prepare the environment
        run: |
          su - sherlock 
          whoami 
          echo "export MODULEPATH=/home/sherlock/.local/share/modulefiles:\$MODULEPATH" >> /home/sherlock/.bashrc
          echo "module use --append /home/sherlock/.local/share/modulefiles/"  >> /home/sherlock/.bashrc
          echo "source /etc/profile.d/z00_lmod.sh" >> /home/sherlock/.bashrc
      - name: Test R module
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          echo $MODULEPATH
          module spider
          module load R/${{ env.R_VERSION }}
          R -e "print('hello')"   
        if: always()
      - name: Download repository
        working-directory: /home/sherlock
        run: | 
          su - sherlock 
          git clone https://github.com/the-tobias-project/odbc-module
          cd odbc-module 
          git checkout $(echo $GITHUB_REF | sed 's/refs\/heads\///')
      - name: Install the module
        working-directory: /home/sherlock/odbc-module
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          mkdir -p ~/.R/
          # lines below not needed because we are using package binaries for R, but kept as reference
          #echo "CC=/opt/rh/devtoolset-10/root/bin/gcc" > ~/.R/Makevars
          #echo "CXX=/opt/rh/devtoolset-10/root/bin/g++" >> ~/.R/Makevars
          #source /opt/rh/devtoolset-${{ env.DEVTOOLSET_VERSION }}/enable
          export R_USER=$USER
          make install check=false
      - name: Configure
        working-directory: /home/sherlock/odbc-module
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          make configure group=false
        if: always()
      - name: Set environment
        working-directory: /home/sherlock/odbc-module
        run: |
          su - sherlock
          source /home/sherlock/.bashrc
          make setenv group=false
      - name: Docker set environment secrets
        working-directory: /home/sherlock/odbc-module
        env:
          __DATABRICKS_HOSTNAME: ${{ secrets.DATABRICKS_HOSTNAME }}
          __DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          __DATABRICKS_HTTP_PATH: ${{ secrets.DATABRICKS_HTTP_PATH }}    
          __TEST_SECRET: ${{ secrets.TEST_SECRET }}"
        run: |
          su - sherlock
          source /home/sherlock/.bashrc
          # overload
          export DATABRICKS_HOSTNAME=${__DATABRICKS_HOSTNAME}
          export DATABRICKS_TOKEN=${__DATABRICKS_TOKEN}
          export DATABRICKS_HTTP_PATH=${__DATABRICKS_HTTP_PATH}    
          echo "Test secret is: ${__TEST_SECRET}"
          module spider
          module load databricks-odbc//${{ env.R_VERSION }}
          R -e "library(loaddatabricks); con <- connect_cluster("~/.env"); library(DBI); dbListTables(con)"
        if: always()
      - name: Create tarball of artifacts
        run: tar -czvf base.tar.gz /home/sherlock/odbc-module
        working-directory: /home/sherlock
        if: ${{ github.event_name == 'pull_request' }}
      - name: Publish artifact to release page
        uses: actions/upload-release-asset@v1
        with:
          asset_path: base.tar.gz 
          asset_name: odbc-centos7-R_${{ env.R_VERSION }}-devtoolset_${{ env.DEVTOOLSET_VERSION }}-unixodbc_${{ env.UNIXODBC_VERSION }}.tar.gz 
          asset_content_type: application/gzip 
          tag_name: ${{ github.ref }} 
          repository: ${{ env.REPOSITORY }}
        if: ${{ github.event_name == 'pull_request' }}
