name: base

on:
  push:
    branches: [ "main" ]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    name: build

    runs-on: ubuntu-20.04

    container:
      image: centos:7.9.2009
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          yum update -y && yum makecache && yum clean all
          yum install -y gcc gcc-c++ kernel-devel dnf
          yum install -y epel-release 
          yum install -y Lmod git curl

          export R_VERSION=4.2.2
          curl -O https://cdn.rstudio.com/r/rhel-9/pkgs/R-${R_VERSION}-1-1.x86_64.rpm
          dnf install -y R-${R_VERSION}-1-1.x86_64.rpm
          ln -s /opt/R/${R_VERSION}/bin/R /usr/local/bin/R
          ln -s /opt/R/${R_VERSION}/bin/Rscript /usr/local/bin/Rscript
          useradd -m sherlock
      - name: Create Lua module for R 4.2.2
        run: |
          su - sherlock
          mkdir -p /home/sherlock/.local/share/modulefiles
          echo "#%Module" > /home/sherlock/.local/share/modulefiles/R-4.2.2.lua
          echo "setenv('R_HOME', '/opt/R/4.2.2')" >> /home/sherlock/.local/share/modulefiles/R-4.2.2.lua
          echo "prepend_path('PATH', '/opt/R/4.2.2/bin')" >> /home/sherlock/.local/share/modulefiles/R-4.2.2.lua
          echo "prepend_path('LD_LIBRARY_PATH', '/opt/R/4.2.2/lib64')" >> /home/sherlock/.local/share/modulefiles/R-4.2.2.lua
      - name: Install the package
        run: |
          source /usr/share/Modules/init/bash
          su - sherlock
          git clone https://github.com/the-tobias-project/odbc-module
          cd odbc-module
          make install check=false
      - name: Configure
        run: |
          su - sherlock
          make configure group=false
      - name: Setenv
        run: |
          su - sherlock
          make setenv group=false
          source /home/sherlock/.bashrc
          module spider | grep databricks
