name: base

on:
  push:
    branches: [ "main" ]

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*


jobs:
  build:
    name: build

    runs-on: ubuntu-20.04

    container:
      image: centos:7.9.2009
      options: --user root

    env:
      R_VERSION: "4.2.0"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare environment
        run: |
          yum update -y && yum makecache && yum clean all
          yum install -y gcc gcc-c++ kernel-devel dnf
          yum install -y epel-release 
          yum install -y Lmod git curl
          export R_VERSION=${{ env.R_VERSION }}
          curl -O https://cdn.rstudio.com/r/rhel-9/pkgs/R-${{ env.R_VERSION }}-1-1.x86_64.rpm
          dnf install -y R-${{ env.R_VERSION }}-1-1.x86_64.rpm
          ln -s /opt/R/${{ env.R_VERSION }}/bin/R /usr/local/bin/R
          ln -s /opt/R/${{ env.R_VERSION }}/bin/Rscript /usr/local/bin/Rscript
          useradd -m sherlock
      - name: Create Lua module for R version
        run: |
          mkdir -p /home/sherlock/.local/share/modulefiles
          echo "#%Module" > /home/sherlock/.local/share/modulefiles/R-${{ env.R_VERSION }}.lua
          echo "setenv('R_HOME', '/opt/R/${{ env.R_VERSION }}')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "prepend_path('PATH', '/opt/R/${{ env.R_VERSION }}/bin')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
          echo "prepend_path('LD_LIBRARY_PATH', '/opt/R/${{ env.R_VERSION }}/lib64')" >> /home/sherlock/.local/share/modulefiles/R/${{ env.R_VERSION }}.lua
        shell: bash
      - name: Prepare the environment
        run: |
          su - sherlock 
          echo "export MODULEPATH=/home/sherlock/.local/share/modulefiles:\$MODULEPATH" >> /home/sherlock/.bashrc
          echo "module use --append /home/sherlock/.local/share/modulefiles/"  >> /home/sherlock/.bashrc
          echo "source /etc/profile.d/z00_lmod.sh" >> /home/sherlock/.bashrc
      - name: Test R module
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          echo $MODULEPATH
          module spider
      - name: Install the package
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          git clone https://github.com/the-tobias-project/odbc-module
          cd odbc-module && make install check=false
      - name: Configure
        run: |
          su - sherlock 
          source /home/sherlock/.bashrc
          cd odbc-module && make configure group=false
      - name: Setenv
        run: |
          su - sherlock
          source /home/sherlock/.bashrc
          make setenv group=false
          module spider databricks | grep R/${{ inputs.R_VERSION }}
